name: Python Testing and Test Coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python_code/requirements.txt
    - name: pytest
      id: pytest
      uses: alexanderdamiani/pytester-cov@v1.0.1
      with:
        pytest-root-dir: './python_code/code'
        cov-omit-list: 'test/*, temp/main3.py, temp/main4.py'
        cov-threshold-single: 80
        cov-threshold-total: 30
    - name: Coverage total fail - exit
      if: ${{ steps.pytest.outputs.cov-threshold-total-fail == 'true' }}
      run: |
        echo "cov single fail ${{ steps.pytest.outputs.cov-threshold-total-fail }}"
        exit 1
    - name: Commit pytest coverage table
      uses: peter-evans/commit-comment@v1
      with:
        body: ${{ steps.pytest.outputs.output-table }}