name: Python Testing and Test Coverage
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python_code/requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        python -m pytest --cov=./python_code/tests > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2