name: 'coverage'
on:
  pull_request:
    branches:
        - master
jobs:
  coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: mattallty/jest-github-action@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            test-command: "npm run test"