name: 'coverage'
on:
  pull_request:
    branches:
        - master
jobs:
  coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - run: npm ci
        - name: Run Tests
          run: npx jest --coverage --json --outputFile=/home/runner/work/_actions/mattallty/jest-github-action/v1/dist/jest.results.json
        - uses: mattallty/jest-github-action@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            test-command: "echo done"