name: 'coverage'
on:
  pull_request:
    branches:
        - master
  push:
    branches:
        - master
jobs:
  coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - run: npm ci
        - name: Run Tests
          run: npm run test
        - name: Coveralls
          uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            path-to-lcov: "./docs/coverage/lcov.info"