name: 'coverage'
on:
  pull_request:
    branches:
        - master
jobs:
  coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - uses: artiomtr/jest-coverage-report-action@v1.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            test_script: npx jest --silent --ci --coverage --coverageReporters="text" --coverageReporters="text-summary"