name: Build and publish frontend test coverage 
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and publish frontend test coverage 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Run Jest tests and generate coverage report
      run: npm test
    - name: Deploy Frontend Coverage Report
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        branch: gh-pages
        folder: docs/coverage 