name: Build and publish test coverage 
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and publish test coverage 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python_code/requirements.txt
    - name: Run pytest tests.
    - run: pytest --cov=./python_code/code --cov-report=html:./docs/python_coverage test
    - name: Deploy Backend Coverage Report
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        branch: gh-pages-backend-coverage 
        folder: docs/coverage 