name: Build and publish test coverage 
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and publish test coverage 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Run Jest tests and generate coverage report
      run: npm test
    - name: Publish test coverage report
      uses: EndBug/add-and-commit@v4
      with:
        add: docs
        force: true
        message: Add generated docs